swagger: '2.0'
info:
  description: Amazon PA API ドキュメント
  version: 0.0.1
  title: Amazon PA REST APIs
host: amazon-pa.herokuapp.com
basePath: /
tags:
  - name: pa
    description: PA API
schemes:
  - http
  - https
paths:
  /ping:
    get:
      tags:
        - pa
      summary: Ping/Pong
      description: Ping/Pong
      produces:
        - application/json
      responses:
        '200':
          description: 成功
        '400':
          description: エラー
  /{keyword}:
    get:
      tags:
        - pa
      summary: search by keyword
      description: search by keyword
      produces:
        - application/json
      parameters:
        - name: keyword
          type: string
          in: path
          description: 検索キーワード
          required: true
        - name: sort
          type: string
          in: query
          description: ソート指定(byprice/bypricedesc/byreview/bydate)
      responses:
        '200':
          description: 成功
        '400':
          description: エラー
